//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        

        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Guid ActivationCode { get; internal set; }
        public string ConfirmPassword { get; internal set; }

        private string emailID;
        internal bool IsEmailVerified;

        public string GetEmailID()
        {
            return emailID;
        }

        public void SetEmailID(string value)
        {
            emailID = value;
        }
    }
}
